# Podio Glossary - PSS Terms & Abbreviations

## Project Roles & People

**PM (Project Manager)**
The PSS person in charge of the overall project. Handles budgets, schedules, GC relationships, and big decisions.

**OC (Operations Coordinator)**
Supports the PM with scheduling, task tracking, documentation, and keeping the project organized in Podio.

**FOCS (Field Operations Coordinator / Supervisor)**
[NEEDS VERIFICATION: Exact role definition] Coordinates field activities and crew schedules.

**Foreman**
Leads the crew on-site. Executes the work and manages day-to-day field operations.

**GC (General Contractor)**
The main contractor who hired PSS. They manage the overall construction project and coordinate all subcontractors.

---

## Project Identification

**Job # (Job Number)**
A unique number assigned to each project (e.g., 2024-015). Used to identify and track projects.

**Job ID**
The combination of Job # and Job Name, auto-generated by Podio (e.g., "2024-015 - Downtown Office Foundation"). This is the full project identifier.

**Job Name**
The descriptive name of the project (e.g., "Downtown Office Foundation").

---

## Project Organization

**Division**
The type of work PSS is doing on the project. Options:
- **Concrete** - Foundations, slabs, concrete structures (most common)
- **Drywall** - Interior walls and finishing
- **Other** - Anything that doesn't fit the above

Division determines which task templates get auto-created for the project.

**Scopes**
The specific types of work included in the project contract. Multiple scopes can be selected. Examples:
- Earthwork
- Utilities
- Foundations
- Concrete
- Framing
- Other trades

---

## Project Stages

PSS projects move through **5 stages** in order:

**1. Pre-Construction**
Planning phase: permits, submittals, RFIs, safety setup, scheduling. Happens before you break ground.

**2. Mobilization**
Getting ready to start work: site setup, equipment delivery, crew assignment, final prep.

**3. Construction**
Active work phase: building, daily reports, managing tasks, dealing with issues as they come up.

**4. Demobilization**
Wrapping up: cleanup, equipment return, punch list items, final inspections.

**5. Retainage**
Final billing and closeout: waiting for final payment, submitting closeout documents, project archive.

Each stage has its own set of tasks that auto-populate when you activate that stage.

**Current Stage Status**
The field in the Project that shows which stage is active right now (e.g., "Construction Active"). When you change this, Podio creates tasks for that stage.

---

## Tasks & Work Tracking

**Task**
A specific to-do item that needs to be completed. Tasks are the building blocks of project work.

**Subtask**
A smaller task that's part of a larger parent task. Example: "Pour Foundation" might have subtasks like "Set up forms", "Place rebar", "Call for inspection".

**Task #**
The unique number for each task in the entire Tasks app.

**Stage Task #**
The task number within a specific stage (e.g., Pre-Construction Task #5). Helps you reference tasks in conversation.

**Recurring Task**
A task that repeats on a schedule (e.g., weekly safety meetings). Podio automatically duplicates these based on automation settings.

**Task Type**
Category field that identifies what kind of task it is:
- **Task** - Standard one-time to-do
- **Recurring** - Repeats on a schedule
- **Subtask** - Child task of a parent task

**Task Status**
Shows where the task is:
- **Pending** (red) - Not started yet, might be waiting on something
- **In Progress** (yellow) - Actively being worked on
- **Complete** (green) - Done!

**Responsible**
The PSS person assigned to complete the task. This is who gets notified and who's accountable.

**Due Date**
When the task needs to be finished.

**Dependencies**
When one task can't start until another finishes. Example: "Pour foundation" depends on "Foundation inspection passed".

**Independent Task**
A task that can be started right away. Doesn't depend on anything else.

**Dependent Task**
A task that must wait for another task (its prerequisite) to be completed first.

**Prerequisite**
The task that must be completed before a dependent task can start. Example: "Submit plans" is a prerequisite for "Obtain permit".

---

## Documents & Requests

**Submittal**
Documents you send to the GC for approval before starting work (material specs, product data, shop drawings, etc.).

**RFI (Request for Information)**
A formal question you ask the GC when plans, specs, or instructions are unclear.

**COR (Change Order Request)**
A request for additional money or time when the scope of work changes beyond what's in the original contract.

**LOI (Letter of Intent)**
A preliminary agreement that shows the GC intends to hire you, often issued before the full contract is signed.

---

## Podio-Specific Terms

**App**
A Podio database for a specific type of information. PSS uses apps like Projects, Tasks, Stages, Contacts, Safety & Compliance.

**Workspace**
A collection of related Podio apps. PSS's workspace is called **Precision Projects**.

**Relationship Field**
A field that links items between apps. Example: the "Customer / GC" field in Projects links to items in the Contacts app.

**Calculated Field**
A field that auto-calculates based on other fields. Example: "Job ID" is calculated from Job # + Job Name. You can't edit these directly.

**Automation (GlobiFlow)**
Background processes that do things automatically. Examples:
- Creating stages when you create a new project
- Creating tasks when you activate a stage
- Notifying people when a task is completed

**Automation Status**
A field that tracks whether automations have finished running. Values:
- **"1 - Pending Creation"** - Tasks are about to be created
- **"2 - Creation Complete"** - Tasks created, linking in progress
- **"3 - Linking Complete"** - Everything's done

---

## Financial & Contract Terms

**Contract Value**
The total amount the GC has agreed to pay PSS for the project, including any approved change orders.

**Project Budget**
The estimated cost to complete the project (labor, materials, equipment, etc.). Managed by the PM.

**Variance**
The difference between budget and actual costs. Calculated automatically (Project Budget minus costs). [NEEDS VERIFICATION: Exact calculation source]

**Retainage**
Money the GC holds back (usually 5-10%) until the project is completely finished and all issues are resolved.

---

## Safety & Compliance

**811 Locate**
Calling the utility locate service (811) before digging to mark underground utilities. Required by law.

**SSSP (Site-Specific Safety Plan)**
A safety plan tailored to the specific hazards and conditions of the project site.

**Badging**
Security badges or credentials required to access certain job sites.

---

## Common Abbreviations

- **GC** - General Contractor
- **PM** - Project Manager
- **OC** - Operations Coordinator
- **FOCS** - Field Operations Coordinator/Supervisor
- **RFI** - Request for Information
- **COR** - Change Order Request
- **LOI** - Letter of Intent
- **SSSP** - Site-Specific Safety Plan
- **PSS** - Precision Site Services (that's you!)

---

**Still confused about a term?** Ask your PM or OC—they're happy to explain!
